---
- hosts: all
  remote_user: ubuntu
  become: yes #usar root

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
    
    - name: Init nginx
      service: 
        name: nginx
        state: started